// Mock AI integrations for Nano Banana and ElevenLabs

// Mock artwork database - in production, these would be generated by Nano Banana AI
const mockArtwork = {
  fish: {
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9ImZpc2hHcmFkaWVudCIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+CjxzdG9wIG9mZnNldD0iMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiNGRjYxNDQ7c3RvcC1vcGFjaXR5OjEiIC8+CjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6I0ZGQzk0NztzdG9wLW9wYWNpdHk6MSIgLz4KPC9saW5lYXJHcmFkaWVudD4KPC9kZWZzPgo8ZWxsaXBzZSBjeD0iMjAwIiBjeT0iMTUwIiByeD0iMTIwIiByeT0iNjAiIGZpbGw9InVybCgjZmlzaEdyYWRpZW50KSIgc3Ryb2tlPSIjRkY0NTAwIiBzdHJva2Utd2lkdGg9IjMiLz4KPHBvbHlnb24gcG9pbnRzPSI4MCwxNTAgMTIwLDEyMCAxMjAsMTgwIiBmaWxsPSJ1cmwoI2Zpc2hHcmFkaWVudCkiIHN0cm9rZT0iI0ZGNDUwMCIgc3Ryb2tlLXdpZHRoPSIzIi8+CjxjaXJjbGUgY3g9IjI0MCIgY3k9IjEzMCIgcj0iMTIiIGZpbGw9IiMwMDAwMDAiLz4KPHN0cmlwZSB4MT0iMTYwIiB5MT0iMTQwIiB4Mj0iMjgwIiB5Mj0iMTQwIiBzdHJva2U9IiNGRjQ1MDAiIHN0cm9rZS13aWR0aD0iMiIvPgo8c3RyaXBlIHgxPSIxNjAiIHkxPSIxNjAiIHgyPSIyODAiIHkyPSIxNjAiIHN0cm9rZT0iI0ZGNDUwMCIgc3Ryb2tlLXdpZHRoPSIyIi8+Cjx0ZXh0IHg9IjIwMCIgeT0iMjgwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjNjY2NjY2IiBmb250LXNpemU9IjE0Ij7wn5qAIE5hbm8gQmFuYW5hIEFJIEVuaGFuY2VkPC90ZXh0Pgo8L3N2Zz4=',
    style: 'vibrant-tropical',
    description: 'A beautiful tropical fish with flowing fins and vibrant orange-coral gradients'
  },
  cat: {
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9ImNhdEdyYWRpZW50IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj4KPHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6IzdDM0FFQztzdG9wLW9wYWNpdHk6MSIgLz4KPHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojRkY5Q0U0O3N0b3Atb3BhY2l0eToxIiAvPgo8L2xpbmVhckdyYWRpZW50Pgo8L2RlZnM+CjxlbGxpcHNlIGN4PSIyMDAiIGN5PSIxODAiIHJ4PSI4MCIgcnk9IjUwIiBmaWxsPSJ1cmwoI2NhdEdyYWRpZW50KSIgc3Ryb2tlPSIjNkM2M0ZGIiBzdHJva2Utd2lkdGg9IjMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTIwIiByPSI0NSIgZmlsbD0idXJsKCNjYXRHcmFkaWVudCkiIHN0cm9rZT0iIzZDNjNGRiIgc3Ryb2tlLXdpZHRoPSIzIi8+Cjxwb2x5Z29uIHBvaW50cz0iMTcwLDkwIDI2MCw5MCAyNDUsMTMwIiBmaWxsPSJ1cmwoI2NhdEdyYWRpZW50KSIgc3Ryb2tlPSIjNkM2M0ZGIiBzdHJva2Utd2lkdGg9IjMiLz4KPHBvbHlnb24gcG9pbnRzPSIxNTAsOTAgMjMwLDkwIDIxNSwxMzAiIGZpbGw9InVybCgjY2F0R3JhZGllbnQpIiBzdHJva2U9IiM2QzYzRkYiIHN0cm9rZS13aWR0aD0iMyIvPgo8Y2lyY2xlIGN4PSIxODUiIGN5PSIxMTAiIHI9IjYiIGZpbGw9IiMwMDAwMDAiLz4KPGNpcmNsZSBjeD0iMjE1IiBjeT0iMTEwIiByPSI2IiBmaWxsPSIjMDAwMDAwIi8+Cjxwb2x5Z29uIHBvaW50cz0iMjAwLDEyNSAyMDUsMTM1IDE5NSwxMzUiIGZpbGw9IiNGRjY5QjQiLz4KPGVsbGlwc2UgY3g9IjEyMCIgY3k9IjIwMCIgcng9IjQwIiByeT0iMTAiIGZpbGw9InVybCgjY2F0R3JhZGllbnQpIiBzdHJva2U9IiM2QzYzRkYiIHN0cm9rZS13aWR0aD0iMiIvPgo8dGV4dCB4PSIyMDAiIHk9IjI4MCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzY2NjY2NiIgZm9udC1zaXplPSIxNCI+8J+QsiBOYW5vIEJhbmFuYSBBSSBFbmhhbmNlZDwvdGV4dD4KPC9zdmc+',
    style: 'cute-gradient',
    description: 'An adorable cat with purple-pink gradients and playful features'
  },
  house: {
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9ImhvdXNlR3JhZGllbnQiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMTAwJSIgeTI9IjEwMCUiPgo8c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojM0I4MkY2O3N0b3Atb3BhY2l0eToxIiAvPgo8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiM4QjVDRjY7c3RvcC1vcGFjaXR5OjEiIC8+CjwvbGluZWFyR3JhZGllbnQ+CjwvZGVmcz4KPHJlY3QgeD0iMTMwIiB5PSIxNDAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiBmaWxsPSJ1cmwoI2hvdXNlR3JhZGllbnQpIiBzdHJva2U9IiMyNTYzRUIiIHN0cm9rZS13aWR0aD0iMyIvPgo8cG9seWdvbiBwb2ludHM9IjEyMCwxNDAgMjAwLDgwIDI4MCwxNDAiIGZpbGw9IiNFRjQ0NDQiIHN0cm9rZT0iI0RDMjYyNiIgc3Ryb2tlLXdpZHRoPSIzIi8+CjxyZWN0IHg9IjE2MCIgeT0iMTgwIiB3aWR0aD0iMzAiIGhlaWdodD0iNjAiIGZpbGw9IiM5MjQwMDAiIHN0cm9rZT0iIzc5MkMwMCIgc3Ryb2tlLXdpZHRoPSIyIi8+CjxyZWN0IHg9IjIxMCIgeT0iMTYwIiB3aWR0aD0iMzAiIGhlaWdodD0iMzAiIGZpbGw9IiM2NkNDRkYiIHN0cm9rZT0iIzM5OTREQSJ9VDJva2Utd2lkdGg9IjIiLz4KPGVsbGlwc2UgY3g9IjIwMCIgY3k9IjI2MCIgcng9IjgwIiByeT0iMTAiIGZpbGw9IiMxMEI5ODEiIHN0cm9rZT0iIzA1OTY2OSIgc3Ryb2tlLXdpZHRoPSIyIi8+Cjx0ZXh0IHg9IjIwMCIgeT0iMjgwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSIjNjY2NjY2IiBmb250LXNpemU9IjE0Ij7wn4+hIE5hbm8gQmFuYW5hIEFJIEVuaGFuY2VkPC90ZXh0Pgo8L3N2Zz4=',
    style: 'architectural-modern',
    description: 'A charming modern house with blue gradients and architectural details'
  },
  tree: {
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9InRyZWVHcmFkaWVudCIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+CjxzdG9wIG9mZnNldD0iMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiMxMEI5ODE7c3RvcC1vcGFjaXR5OjEiIC8+CjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6IzM0RDA2NDtzdG9wLW9wYWNpdHk6MSIgLz4KPC9saW5lYXJHcmFkaWVudD4KPC9kZWZzPgo8cmVjdCB4PSIxOTAiIHk9IjE4MCIgd2lkdGg9IjIwIiBoZWlnaHQ9IjgwIiBmaWxsPSIjOTI0MDAwIiBzdHJva2U9IiM3MjJGMDAiIHN0cm9rZS13aWR0aD0iMyIvPgo8Y2lyY2xlIGN4PSIyMDAiIGN5PSIxMjAiIHI9IjcwIiBmaWxsPSJ1cmwoI3RyZWVHcmFkaWVudCkiIHN0cm9rZT0iIzA1OTY2OSIgc3Ryb2tlLXdpZHRoPSI0Ii8+CjxjaXJjbGUgY3g9IjE2MCIgY3k9IjEwMCIgcj0iMzAiIGZpbGw9InVybCgjdHJlZUdyYWRpZW50KSIgc3Ryb2tlPSIjMDU5NjY5IiBzdHJva2Utd2lkdGg9IjIiLz4KPGNpcmNsZSBjeD0iMjQwIiBjeT0iMTEwIiByPSIzNSIgZmlsbD0idXJsKCN0cmVlR3JhZGllbnQpIiBzdHJva2U9IiMwNTk2NjkiIHN0cm9rZS13aWR0aD0iMiIvPgo8Y2lyY2xlIGN4PSIyMDAiIGN5PSI4MCIgcj0iMjUiIGZpbGw9InVybCgjdHJlZUdyYWRpZW50KSIgc3Ryb2tlPSIjMDU5NjY5IiBzdHJva2Utd2lkdGg9IjIiLz4KPGVsbGlwc2UgY3g9IjIwMCIgY3k9IjI3MCIgcng9IjYwIiByeT0iOCIgZmlsbD0iIzA1OTY2OSIgc3Ryb2tlPSIjMDQ3ODU3IiBzdHJva2Utd2lkdGg9IjIiLz4KPHR7eHQgeD0iMjAwIiB5PSIyOTAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM2NjY2NjYiIGZvbnQtc2l6ZT0iMTQiPvCfkrMgTmFubyBCYW5hbmEgQUkgRW5oYW5jZWQ8L3RleHQ+Cjwvc3ZnPg==',
    style: 'natural-organic',
    description: 'A lush tree with vibrant green gradients and organic flowing shapes'
  },
  car: {
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9ImNhckdyYWRpZW50IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj4KPHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6I0ZGNDQ0NDtzdG9wLW9wYWNpdHk6MSIgLz4KPHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojRkZBQTAwO3N0b3Atb3BhY2l0eToxIiAvPgo8L2xpbmVhckdyYWRpZW50Pgo8L2RlZnM+CjxyZWN0IHg9IjEwMCIgeT0iMTYwIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjYwIiBmaWxsPSJ1cmwoI2NhckdyYWRpZW50KSIgc3Ryb2tlPSIjRkYyRjAwIiBzdHJva2Utd2lkdGg9IjMiLz4KPHJlY3QgeD0iMTMwIiB5PSIxMzAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMzAiIGZpbGw9InVybCgjY2FyR3JhZGllbnQpIiBzdHJva2U9IiNGRjJGMDAiIHN0cm9rZS13aWR0aD0iMyIvPgo8Y2lyY2xlIGN4PSIxNDAiIGN5PSIyMzAiIHI9IjI1IiBmaWxsPSIjMzMzMzMzIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMyIvPgo8Y2lyY2xlIGN4PSIyNjAiIGN5PSIyMzAiIHI9IjI1IiBmaWxsPSIjMzMzMzMzIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMyIvPgo8cmVjdCB4PSIxNTAiIHk9IjEzNSIgd2lkdGg9IjQwIiBoZWlnaHQ9IjIwIiBmaWxsPSIjNjZDQ0ZGIiBzdHJva2U9IiMzOTk0REEiIHN0cm9rZS13aWR0aD0iMiIvPgo8cmVjdCB4PSIyMTAiIHk9IjEzNSIgd2lkdGg9IjQwIiBoZWlnaHQ9IjIwIiBmaWxsPSIjNjZDQ0ZGIiBzdHJva2U9IiMzOTk0REEiIHN0cm9rZS13aWR0aD0iMiIvPgo8dGV4dCB4PSIyMDAiIHk9IjI4MCIgdGV4dC1hbmNob3I9Im1pZGRsZSIgZmlsbD0iIzY2NjY2NiIgZm9udC1zaXplPSIxNCI+8J+OiCBOYW5vIEJhbmFuYSBBSSBFbmhhbmNlZDwvdGV4dD4KPC9zdmc+',
    style: 'retro-racing',
    description: 'A stylish racing car with red-orange gradients and sleek design'
  },
  default: {
    imageUrl: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAwIiBoZWlnaHQ9IjMwMCIgdmlld0JveD0iMCAwIDQwMCAzMDAiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxkZWZzPgo8cmFkaWFsR3JhZGllbnQgaWQ9ImRlZmF1bHRHcmFkaWVudCI+CjxzdG9wIG9mZnNldD0iMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiM4QjVDRjY7c3RvcC1vcGFjaXR5OjEiIC8+CjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6IzNEQTU4QTtzdG9wLW9wYWNpdHk6MSIgLz4KPC9yYWRpYWxHcmFkaWVudD4KPC9kZWZzPgo8Y2lyY2xlIGN4PSIyMDAiIGN5PSIxNTAiIHI9IjEwMCIgZmlsbD0idXJsKCNkZWZhdWx0R3JhZGllbnQpIiBzdHJva2U9IiM2QzYzRkYiIHN0cm9rZS13aWR0aD0iNSIvPgo8cG9seWdvbiBwb2ludHM9IjE1MCwxMDAuMjAwLDUwIDI1MCwxMDAuMjAwLDE1MCAyMDAsMjUwIDMwMCwyMDAiIGZpbGw9InVybCgjZGVmYXVsdEdyYWRpZW50KSIgc3Ryb2tlPSIjNkM2M0ZGIiBzdHJva2Utd2lkdGg9IjMiLz4KPHR7eHQgeD0iMjAwIiB5PSIyODAiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiM2NjY2NjYiIGZvbnQtc2l6ZT0iMTQiPvCfjK4gTmFubyBCYW5hbmEgQUkgRW5oYW5jZWQ8L3RleHQ+Cjwvc3ZnPg==',
    style: 'abstract-creative',
    description: 'A beautiful abstract creation with vibrant gradients and artistic flair'
  }
};

// Mock music themes for ElevenLabs
const mockMusicThemes = {
  fish: {
    audioUrl: null, // In demo mode, no actual audio files
    theme: 'underwater-ambient',
    description: 'Calming ocean sounds with bubbling water and gentle waves'
  },
  cat: {
    audioUrl: null,
    theme: 'playful-whimsical',
    description: 'Light, bouncy melody with soft piano and gentle purring sounds'
  },
  house: {
    audioUrl: null,
    theme: 'cozy-domestic',
    description: 'Warm, homey atmosphere with acoustic guitar and gentle harmonies'
  },
  tree: {
    audioUrl: null,
    theme: 'forest-nature',
    description: 'Natural forest sounds with birds chirping and rustling leaves'
  },
  car: {
    audioUrl: null,
    theme: 'retro-driving',
    description: 'Upbeat synthwave music perfect for a road trip adventure'
  },
  default: {
    audioUrl: null,
    theme: 'creative-inspiration',
    description: 'Ambient electronic music to inspire creativity and focus'
  }
};

// Simulate Nano Banana AI artwork generation
export async function generateArtwork(drawingData, prompt) {
  // Extract object type from prompt
  const objectType = extractObjectFromPrompt(prompt);
  
  // Simulate processing time
  await new Promise(resolve => setTimeout(resolve, 2000 + Math.random() * 2000)); // 2-4 seconds
  
  // Get appropriate artwork or fallback to default
  const artwork = mockArtwork[objectType.toLowerCase()] || mockArtwork.default;
  
  return {
    success: true,
    imageUrl: artwork.imageUrl,
    style: artwork.style,
    description: artwork.description,
    originalPrompt: prompt,
    processingTime: Math.round(2000 + Math.random() * 2000), // ms
    aiProvider: 'Nano Banana AI',
    enhancement: {
      colorCorrection: true,
      styleTransfer: true,
      detailEnhancement: true,
      artisticFilter: artwork.style
    }
  };
}

// Simulate ElevenLabs background music generation
export async function generateBackgroundMusic(drawingData, prompt) {
  const objectType = extractObjectFromPrompt(prompt);
  
  // Simulate processing time
  await new Promise(resolve => setTimeout(resolve, 1500 + Math.random() * 1000)); // 1.5-2.5 seconds
  
  const music = mockMusicThemes[objectType.toLowerCase()] || mockMusicThemes.default;
  
  return {
    success: true,
    audioUrl: music.audioUrl, // null in demo mode
    theme: music.theme,
    description: music.description,
    duration: 30, // seconds
    aiProvider: 'ElevenLabs',
    generationParams: {
      mood: 'calm-inspiring',
      tempo: 'medium',
      instruments: ['ambient', 'acoustic'],
      theme: objectType
    }
  };
}

// Combined AI processing function
export async function processDrawingWithAI(drawingData, prompt) {
  try {
    // Process artwork and music in parallel
    const [artworkResult, musicResult] = await Promise.all([
      generateArtwork(drawingData, prompt),
      generateBackgroundMusic(drawingData, prompt)
    ]);
    
    return {
      success: true,
      artwork: artworkResult,
      music: musicResult,
      totalProcessingTime: Math.max(
        artworkResult.processingTime,
        musicResult ? 1500 + Math.random() * 1000 : 0
      ),
      timestamp: new Date().toISOString()
    };
    
  } catch (error) {
    console.error('AI processing error:', error);
    
    return {
      success: false,
      error: 'Failed to process drawing with AI',
      fallback: {
        artwork: mockArtwork.default,
        music: mockMusicThemes.default
      }
    };
  }
}

// Helper function to extract object from prompt
function extractObjectFromPrompt(prompt) {
  const words = prompt.toLowerCase().split(' ');
  const articles = ['a', 'an', 'the', 'draw', 'please', 'some'];
  return words.find(word => !articles.includes(word) && word.length > 2) || 'object';
}

// Generate random drawing prompts
export function generateRandomPrompt() {
  const prompts = [
    'Draw a fish',
    'Draw a cat',
    'Draw a house', 
    'Draw a tree',
    'Draw a car',
    'Draw a flower',
    'Draw a bird',
    'Draw a sun',
    'Draw a butterfly',
    'Draw a dog',
    'Draw a boat',
    'Draw a mountain'
  ];
  
  return prompts[Math.floor(Math.random() * prompts.length)];
}

// Validate drawing matches prompt (basic heuristics)
export function validateDrawingContent(drawingData, prompt) {
  const objectType = extractObjectFromPrompt(prompt);
  const { strokes } = drawingData;
  
  if (!strokes || strokes.length === 0) {
    return { isValid: false, reason: 'No drawing detected' };
  }
  
  // Basic validation based on stroke count and complexity
  const strokeCount = strokes.length;
  const totalPoints = strokes.reduce((sum, stroke) => sum + stroke.points.length, 0);
  
  let minStrokes = 2;
  let maxStrokes = 20;
  
  // Object-specific expectations
  switch (objectType.toLowerCase()) {
    case 'fish':
      minStrokes = 2; // body + tail minimum
      break;
    case 'cat':
      minStrokes = 3; // body + head + ears minimum
      break;
    case 'house':
      minStrokes = 3; // walls + roof + door minimum
      break;
    case 'tree':
      minStrokes = 2; // trunk + foliage minimum
      break;
    case 'car':
      minStrokes = 3; // body + wheels minimum
      break;
    default:
      minStrokes = 1;
  }
  
  if (strokeCount < minStrokes) {
    return { 
      isValid: false, 
      reason: `Drawing seems incomplete. Expected at least ${minStrokes} strokes for a ${objectType}` 
    };
  }
  
  if (strokeCount > maxStrokes) {
    return { 
      isValid: false, 
      reason: 'Drawing seems overly complex or repetitive' 
    };
  }
  
  if (totalPoints < 10) {
    return { 
      isValid: false, 
      reason: 'Drawing is too simple' 
    };
  }
  
  return { 
    isValid: true, 
    confidence: Math.min(95, 60 + (strokeCount * 5)), 
    analysis: `Reasonable ${objectType} drawing with ${strokeCount} strokes` 
  };
}